name: Pushlog
description: Generates an AI-powered changelog from commits and code changes and posts it to Slack
author: kmakris23

inputs:
  slack_webhook:
    description: Slack webhook URL
    required: true

  openai_api_key:
    description: OpenAI API key
    required: true

  branch:
    description: Branch to monitor
    required: true

  language:
    description: Language code for the changelog (e.g. en, el, fr, de)
    required: false
    default: en

runs:
  using: docker
  image: Dockerfile
